config/routes.rb
Rails.application.routes.draw do
  root to: 'sessions#new'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  get 'search', to: 'skills#search'
  get 'master', to: 'users#master'

  
  resources :users do
    member do
    get :all_skills
    get :yet_skills
    get :set_skill
    
    end
  end
  resources :skills
  resources :categories
  resources :departments
  resources :haveskills
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  
  belongs_to :department
  has_many :skills
  
  has_many :haveskills
  has_many :all_skills,through: :haveskills,source: :skill 
  has_many :yet_skills,through: :haveskills,source: :skill 
  
  
  def yet_skills
    skills = Skill.pluck(:id)
    haveskills  = Haveskill.where(user_id: self.id).pluck(:skill_id)
    yet = skills - haveskills
    yet_skills = Skill.find(yet)
    
  end
  
  
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:show, :all_skills,:edit,:update,:all_skills,:yet_skills,:set_skill]
  before_action :correct_user, only: [:edit,:update,:all_skills, :yet_skills, :set_skill]
  before_action :unrequire_user_logged_in,only: [:new]
  before_action :master_user, only: [:master,:destroy]
  
  def show
    @user = User.find(params[:id])
    
  end
  
  def new
    @user = User.new
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
    
    
  end
  
  def update
        @user = User.find(params[:id])
        
        if @user.update(edit_params)
          flash[:success] = 'ユーザ情報を更新しました。'
          redirect_to @user
        else
          flash[:danger] = 'ユーザ情報の更新に失敗しました。'
          render :edit
      end
  end
  
  def all_skills
    @user = User.find(params[:id])
    @categories = Category.order(display: :asc)
    @skills = Skill.order(created_at: :desc)

    
  end

  def yet_skills
    @user = User.find(params[:id])
    @skills = Skill.pluck(:id)
    @haveskills  = Haveskill.where(user_id: current_user.id).pluck(:skill_id)
    @yet = @skills - @haveskills
    @yet_skills = Skill.where(id: @yet)
    @categories = Category.order(display: :asc)
  end
  
  def set_skill
    skill = params[:skill]
    assessment = params[:assessment]

    
    skillset = current_user.haveskills.find_by(skill_id: skill)
    if (skillset == nil)
      
        skillset = current_user.haveskills.build(skill_id: skill, assessment: assessment)
        if (skillset.save)
              redirect_back(fallback_location: root_path)
              return;
        else
          flash.now[:danger] = 'スキルの登録に失敗しました。'
              redirect_back(fallback_location: root_path)
              return;
        end
    else
      if (skillset.update(skill_id: skill, assessment: assessment))
        redirect_back(fallback_location: root_path)
        return;
      else
        flash.now[:danger] = 'スキルの登録に失敗しました。'
        redirect_back(fallback_location: root_path)
        return;
      end
    end
  end
  
  
  def master
    @categories = Category.all
    @departments = Department.all
    @users = User.all
    @skills = Skill.all
    @haveskills = Haveskill.all
    

  end
  
  def destroy
    @user = User.find(params[:id])
    if @user.skills.count < 1 && @user.haveskills.count < 1
    @user.destroy
    flash[:success] = 'ユーザーを削除しました。'
    redirect_to master_path
    else
    flash[:danger] = '他のスキルか所持スキルと紐づいているため削除できません。'
    redirect_to edit_user_path
  end
end
  
  private

  def user_params
    params.require(:user).permit(:name, :email, :department_id, :extension_number, :password, :password_confirmation)
  end
  
  def edit_params
    params.require(:user).permit(:name, :email, :department_id, :extension_number)
  end
  

  
  def correct_user
    @user = User.find_by(id: params[:id])
    unless @user == current_user || current_user.id == 2
    flash[:danger] = 'その操作はできません'
      redirect_to root_url
    end
  end
  
  
end
  

app/views/users/_assessment.html.erb
<div class="col-xs-offset-10">
      <div class="sidebar-nav affix" role="complementary">
       <div class="panel-group assessment">
  <div class="panel panel-warning">
    <div class="panel-heading">
      <h4 class="panel-title">
        評価基準
      </h4>
    </div>
    <table class="table">
      <tbody>
			<tr>
				<th>　☆：</th>
				<td>なんでも聞いて！</td>
			</tr>
			<tr>
				<th>　◯：</th>
				<td>かなり詳しい</td>
			</tr>
			<tr>
				<th>　△：</th>
				<td>なんとなく知っている</td>
			</tr>
			<tr>
				<th>　×：</th>
				<td>名前だけ知っている<br>なにそれ？</td>
			</tr>
		</tbody>
	</table>

</div>               
</div>
      </div>
    </div>

app/views/users/all_skills.html.erb
   <%= render 'assessment' %>             

<h1 class="text-center">マイスキル登録</h1>
<br>








<ul class="nav nav-pills col-xs-offset-5 col-xs-4">
	<li role="presentation"><%= link_to '未登録スキル',yet_skills_user_path(current_user) %></li>
	<li role="presentation" class="active"><a href="#">全スキル</a></li>
</ul>

<% if @categories.any? %>
<% @categories.each do |category| %>
<div class="panel-group col-xs-offset-2 col-xs-8">
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h4 class="panel-title">
        <%= category.name %>
      </h4>
    </div>

    <% c_map = ["", "☆", "◯", "△", "×"] %>
   
      <ul class="list-group">
        <% category.skills.each do |skill| %>
        <li class="list-group-item">
          <table class="table-condensed table-origin">
            <tbody>
              <tr>
                <td class="col-xs-9 font-origin">　<%= link_to skill.name, skill_path(skill.id) %></td>
                
                
         
                <% if skill.haveskills.find_by(user_id: current_user.id).present? %>      
                <% if skill.haveskills.find_by(user_id: current_user.id).assessment == 1 %>
                
                <td>
                          <div class="btn-group">
                            <%= link_to c_map[1], set_skill_user_path(skill: skill.id, assessment: 1),class: 'btn btn-primary' %>
                            <%= link_to c_map[2], set_skill_user_path(skill: skill.id, assessment: 2),class: 'btn btn-default' %>
                            <%= link_to c_map[3], set_skill_user_path(skill: skill.id, assessment: 3),class: 'btn btn-default' %>
                            <%= link_to c_map[4], set_skill_user_path(skill: skill.id, assessment: 4),class: 'btn btn-default' %>
                          </div>
                </td>
                
               <% elsif skill.haveskills.find_by(user_id: current_user.id).assessment == 2 %>
                <td>
                          <div class="btn-group">
                            <%= link_to c_map[1], set_skill_user_path(skill: skill.id, assessment: 1),class: 'btn btn-default' %>
                            <%= link_to c_map[2], set_skill_user_path(skill: skill.id, assessment: 2),class: 'btn btn-primary' %>
                            <%= link_to c_map[3], set_skill_user_path(skill: skill.id, assessment: 3),class: 'btn btn-default' %>
                            <%= link_to c_map[4], set_skill_user_path(skill: skill.id, assessment: 4),class: 'btn btn-default' %>
                          </div>
                </td>
                
                <% elsif skill.haveskills.find_by(user_id: current_user.id).assessment == 3 %>
                <td>
                          <div class="btn-group">
                            <%= link_to c_map[1], set_skill_user_path(skill: skill.id, assessment: 1),class: 'btn btn-default' %>
                            <%= link_to c_map[2], set_skill_user_path(skill: skill.id, assessment: 2),class: 'btn btn-default' %>
                            <%= link_to c_map[3], set_skill_user_path(skill: skill.id, assessment: 3),class: 'btn btn-primary' %>
                            <%= link_to c_map[4], set_skill_user_path(skill: skill.id, assessment: 4),class: 'btn btn-default' %>
                          </div>
                </td>
                
                 <% elsif skill.haveskills.find_by(user_id: current_user.id).assessment == 4 %>
                <td>
                          <div class="btn-group">
                            <%= link_to c_map[1], set_skill_user_path(skill: skill.id, assessment: 1),class: 'btn btn-default' %>
                            <%= link_to c_map[2], set_skill_user_path(skill: skill.id, assessment: 2),class: 'btn btn-default' %>
                            <%= link_to c_map[3], set_skill_user_path(skill: skill.id, assessment: 3),class: 'btn btn-default' %>
                            <%= link_to c_map[4], set_skill_user_path(skill: skill.id, assessment: 4),class: 'btn btn-primary' %>
                          </div>
                </td>
                
                <% else %>
                <td>
                          <div class="btn-group">
                            <%= link_to c_map[1], set_skill_user_path(skill: skill.id, assessment: 1),class: 'btn btn-default' %>
                            <%= link_to c_map[2], set_skill_user_path(skill: skill.id, assessment: 2),class: 'btn btn-default' %>
                            <%= link_to c_map[3], set_skill_user_path(skill: skill.id, assessment: 3),class: 'btn btn-default' %>
                            <%= link_to c_map[4], set_skill_user_path(skill: skill.id, assessment: 4),class: 'btn btn-default' %>
                          </div>
                </td>
                
                <% end %>
                
                <% else %>
                
                <td>
                          <div class="btn-group">
                            <%= link_to c_map[1], set_skill_user_path(skill: skill.id, assessment: 1),class: 'btn btn-default' %>
                            <%= link_to c_map[2], set_skill_user_path(skill: skill.id, assessment: 2),class: 'btn btn-default' %>
                            <%= link_to c_map[3], set_skill_user_path(skill: skill.id, assessment: 3),class: 'btn btn-default' %>
                            <%= link_to c_map[4], set_skill_user_path(skill: skill.id, assessment: 4),class: 'btn btn-default' %>
                          </div>
                </td>
                <% end %>
                
                
                
                
              </tr>
            </tbody>
          </table>
        </li>
        <% end %>
      </ul>
      

    
  </div>
</div>
<% end %>
<% end %>

app/views/users/edit.html.erb
<%= form_for(@user) do |f| %>
<%= render 'layouts/error_messages', model: f.object %>
<div class="row">
  <div class="col-xs-offset-3 col-xs-6">
    <div class="panel panel-primary">
      
        <div class="panel-heading">登録情報編集</div>
        <div class="panel-body">
        
        <div class="form-group">
            <%= f.label :name, '氏名(フルネーム)' %>
            <%= f.text_field :name, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :email, 'メールアドレス' %>
            <%= f.email_field :email, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :department_id, '所属' %>
            <br>
            <%= f.collection_select :department_id, Department.order(display: :asc), :id, :name, {}, {class: 'form-control'} %>
          </div>
          
          <div class="form-group">
            <%= f.label :extension_number, '内線番号' %>
            <%= f.text_field :extension_number, class: 'form-control' %>
          </div>

          <div class="text-right">
            <%= f.submit '登録する', class: 'btn btn-primary' %>
          </div>
        
      </div>
    </div>
  </div>
</div>
<% end %>

<% if current_user.id == 2 %>
<%= link_to "削除", @user, method: :delete, data: { confirm: "You sure?" }, class: 'btn btn-danger' %>

<% end %>

app/views/users/master.html.erb
マスターメニュー

<h1>カテゴリー</h1>
<%= link_to 'カテゴリー追加',new_category_path, class:"btn btn-default" %>
<table class="table">
  <tr>
    <th>id</th>
    <th>name</th>
    <th>display</th>
  </tr>
  <% @categories.each do |category| %>
  <tr>
    <td><%= category.id %></td>
    <td><%= category.name %></td>
    <td><%= category.display %></td>
    <td><%= link_to '編集',edit_category_path(category.id), class:"btn btn-default" %></td>
    

  </tr>
  <% end %>
</table>


<h1>所属</h1>
<%= link_to '所属追加',new_department_path, class:"btn btn-default" %>

<table class="table">
  <tr>
    <th>id</th>
    <th>name</th>
    <th>display</th>
  </tr>
  <% @departments.each do |department| %>
  <tr>
    <td><%= department.id %></td>
    <td><%= department.name %></td>
    <td><%= department.display %></td>
    <td><%= link_to '編集',edit_department_path(department.id), class:"btn btn-default" %></td>
  </tr>
  <% end %>
</table>



<h1>ユーザー</h1>
<table class="table">
  <tr>
    <th>id</th>
    <th>name</th>
    <th>email</th>
    <th>department</th>
    <th>extension_number</th>
  </tr>
  <% @users.each do |user| %>
  <tr>
    <td><%= user.id %></td>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= user.department.id %>(<%= user.department.name %>)</td>
    <td><%= user.extension_number %></td>
    <td><%= link_to '編集',edit_user_path(user.id), class:"btn btn-default" %></td>

  </tr>
  <% end %>
</table>


<h1>スキル</h1>
<table class="table">
  <tr>
    <th>id</th>
    <th>name</th>
    <th>category</th>
    <th>post_user</th>
    <th>display</th>
  </tr>
  <% @skills.each do |skill| %>
  <tr>
    <td><%= skill.id %></td>
    <td><%= skill.name %></td>
    <td><%= skill.category_id %>(<%= skill.category.name %>)</td>
    <td><%= skill.user_id %>(<%= skill.user.name %>)</td>
    <td><%= skill.display %></td>
    <td><%= link_to '編集',edit_skill_path(skill.id), class:"btn btn-default" %></td>
  </tr>
  <% end %>
</table>

<h1>所持スキル</h1>
<%= link_to '所持スキル追加',new_haveskill_path, class:"btn btn-default" %>


<table class="table">
  <tr>
    <th>id</th>
    <th>assessment</th>
    <th>user</th>
    <th>skill</th>
  </tr>
  <% @haveskills.each do |haveskill| %>
  <tr>
    <td><%= haveskill.id %></td>
    <td><%= haveskill.assessment %></td>
    <td><%= haveskill.user_id %>(<%= haveskill.user.name %>)</td>
    <td><%= haveskill.skill_id %>(<%= haveskill.skill.name %>)</td>
    <td><%= link_to '編集',edit_haveskill_path(haveskill.id), class:"btn btn-default" %></td>

  </tr>
  <% end %>
</table>

app/views/users/new.html.erb
<%= form_for(@user) do |f| %>
<%= render 'layouts/error_messages', model: f.object %>
<div class="row">
  <div class="col-xs-offset-3 col-xs-6">
    <div class="panel panel-primary">
      
        <div class="panel-heading">新規登録</div>
        <div class="panel-body">
        
        <div class="form-group">
            <%= f.label :name, '氏名(フルネーム)' %>
            <%= f.text_field :name, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :email, 'メールアドレス' %>
            <%= f.email_field :email, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :department_id, '所属' %>
            <br>
            <%= f.collection_select :department_id, Department.order(display: :asc), :id, :name, {}, {class: 'form-control'} %>
          </div>
          
          <div class="form-group">
            <%= f.label :extension_number, '内線番号' %>
            <%= f.text_field :extension_number, class: 'form-control' %>
          </div>
          
          <div class="form-group">
            <%= f.label :password, 'パスワード' %>
            <%= f.password_field :password, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :password_confirmation, 'パスワード（確認）' %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
          </div>

          <div class="text-right">
            <%= f.submit '登録する', class: 'btn btn-primary' %>
          </div>
        
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/users/show.html.erb
<h1 class="text-center"><%= @user.name %></h1>


<div class="panel-group col-xs-offset-2 col-xs-8">
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h4 class="panel-title text-center">
      情報
      </h4>
    </div>
    <div class="panel-body">
<div class="">

          <table class="table text-center ">
            <tbody>
              <tr class="">
                <td class="col-xs-2">氏名</td>
                <td class="col-xs-4"><%= @user.name %></td>
              </tr>
              <tr class="">
                <td class="col-xs-2">所属</td>
                <td class="col-xs-4"><%= @user.department.name %></td>
              </tr>
              
              <tr class="">
                <td class="">メールアドレス</td>
                <td class=""><%= @user.email %></td>
              </tr>
              
              <tr class="">
                <td class="">内線番号</td>
                <td class=""><%= @user.extension_number %></td>
              </tr>
            </tbody>
          </table>
          <% if current_user == @user %>
          <div class="text-right"><%= link_to 'マイ情報編集',edit_user_path, class:"btn btn-info" %>
          </div>
          <% end %>
          
     </div>
     </div>
     </div>
     </div>



<div class="panel-group col-xs-offset-2 col-xs-8">
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h4 class="panel-title text-center">
      スキル
      </h4>
    </div>
    <div class="panel-body">
    
     

<h1 class="text-center col-xs-12">☆：<%= @user.haveskills.where(assessment:1).count %></h1>

       <div class="col-xs-offset-1 col-xs-10">
       
        <table class="table table-bordered text-center">
            <tbody>
              <% @user.haveskills.where(assessment:1).joins(skill: :category).order("categories.display").each do |have| %>
              <tr>
                <td class="col-xs-3">
                <%= have.skill.category.name %>
                </td>
                <td class="col-xs-4">
                <%= link_to have.skill.name, skill_path(have.skill_id) %>
                </td>
              </tr>
              <% end %>
            </tbody>
          </table>
          </div>
          <div class="col-xs-12"><p class="box">　</p></div>
          
          
        <h2 class="text-center col-xs-12">◯：<%= @user.haveskills.where(assessment:2).count %></h2>

        <div class="col-xs-offset-1 col-xs-10">
            
          
        <table class="table table-bordered text-center">
            <tbody>
               <% @user.haveskills.where(assessment:2).joins(skill: :category).order("categories.display").each do |have| %>
              <tr>
                <td class="col-xs-3">
               <%= have.skill.category.name %>
                </td>
                <td class="col-xs-4">
                <%= link_to have.skill.name, skill_path(have.skill_id) %>
                </td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
  <div class="col-xs-12"><p class="box">　</p></div>

<% if current_user == @user %>


        
        <h2 class="text-center col-xs-12">△：<%= @user.haveskills.where(assessment:3).count %></h2>

        <div class="col-xs-offset-1 col-xs-10">
          
        <table class="table table-bordered text-center">
            <tbody>
               <% @user.haveskills.where(assessment:3).joins(skill: :category).order("categories.display").each do |have| %>
              <tr>
                <td class="col-xs-3">
               <%= have.skill.category.name %>
                </td>
                <td class="col-xs-4">
                <%= link_to have.skill.name, skill_path(have.skill_id) %>
                </td>
              </tr>
              <% end %>
            </tbody>
          </table>

        </div>
        <div class="col-xs-12"><p class="box">　</p></div>
        
        <h2 class="text-center col-xs-12"> ×：<%= @user.haveskills.where(assessment:4).count %></h2>

        <div class="col-xs-offset-1 col-xs-10">
          
        <table class="table table-bordered text-center">
            <tbody>
               <% @user.haveskills.where(assessment:4).joins(skill: :category).order("categories.display").each do |have| %>
              <tr>
                <td class="col-xs-3">
               <%= have.skill.category.name %>
                </td>
                <td class="col-xs-4">
                <%= link_to have.skill.name, skill_path(have.skill_id) %>
                </td>
              </tr>
              <% end %>
            </tbody>
          </table>

        </div>
        <div class="col-xs-12"><p class="box">　</p></div>
        
<% else %>
<p class = "col-xs-12 text-center">※　△と×の評価は自身のみ確認できます</p>
<% end %>
    </div>
</div>
</div>

app/views/users/yet_skills.html.erb
   <%= render 'assessment' %>   
<h1 class="text-center">マイスキル登録</h1>
<br>

<ul class="nav nav-pills col-xs-offset-5 col-xs-4">
	<li role="presentation" class="active"><a href="#">未登録スキル</a></li>
	<li role="presentation"><%= link_to '全スキル',all_skills_user_path(current_user) %></li>
</ul>





<% if @yet_skills.any? %>
<% @categories.each do |category| %>

<% if @yet_skills.where(category_id: category.id).count != 0 %>

<div class="panel-group col-xs-offset-2 col-xs-8">
<div class="panel panel-primary">


    <div class="panel-heading">
      <h4 class="panel-title">
        <%= category.name %>
      </h4>
    </div>
<% c_map = ["", "☆", "◯", "△", "×"] %>
    
      <ul class="list-group">
          <% @yet_skills.each do |skill| %>
          <% if skill.category_id == category.id %>
        <li class="list-group-item">
          <table class="table-condensed table-origin">
            <tbody>
              <tr>
                <td class="col-xs-9 font-origin">　<%= link_to skill.name, skill_path(skill.id) %></td>
                <td>
                          <div class="btn-group">
                            <%= link_to c_map[1], set_skill_user_path(skill: skill.id, assessment: 1),class: 'btn btn-default' %>
                            <%= link_to c_map[2], set_skill_user_path(skill: skill.id, assessment: 2),class: 'btn btn-default' %>
                            <%= link_to c_map[3], set_skill_user_path(skill: skill.id, assessment: 3),class: 'btn btn-default' %>
                            <%= link_to c_map[4], set_skill_user_path(skill: skill.id, assessment: 4),class: 'btn btn-default' %>
                          </div>
                </td>
              </tr>
            </tbody>
          </table>
        </li>
        <% end %>
        <% end %>
      </ul>
      



</div>
</div>

<% end %>
<% end %>
<% else %>

<p class="col-xs-12 text-center"><br>未登録スキルはありません</p>


<% end %>