config/routes.rb
Rails.application.routes.draw do
  root to: 'sessions#new'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  get 'search', to: 'skills#search'
  get 'master', to: 'users#master'

  
  resources :users do
    member do
    get :all_skills
    get :yet_skills
    get :set_skill
    
    end
  end
  resources :skills
  resources :categories
  resources :departments
  resources :haveskills
end

app/models/skill.rb
class Skill < ApplicationRecord
  belongs_to :category
  belongs_to :user
  has_many :haveskills
  
  validates :name, presence: true
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  before_action :require_user_logged_in
  before_action :master_user, only: [:edit,:update,:destroy]
  def index
    @categories = Category.order(display: :asc)
    @skills = Skill.order(created_at: :desc)
  end
  
  def show
    @skill = Skill.find(params[:id])
  end
  
  def new
    @skill = Skill.new
  end
  
  def create
    @skill = Skill.new(skill_params)
    @skill.user_id = current_user.id

    if @skill.save
      flash[:success] = 'スキルを登録しました。'
      redirect_to new_skill_path
    else
      flash.now[:danger] = 'スキルの登録に失敗しました。'
      render :new
    end
  end
  
  def edit
  @skill = Skill.find(params[:id])
end

def update
  @skill = Skill.find(params[:id])
  
  if @skill.update(edit_params)
          flash[:success] = 'スキルを更新しました。'
          redirect_to edit_skill_path
        else
          flash[:danger] = 'スキルの更新に失敗しました。'
          redirect_to edit_skill_path
  end
end
  
def destroy
    @skill = Skill.find(params[:id])
    if @skill.haveskills.count < 1
    @skill.destroy
    flash[:success] = 'スキルを削除しました。'
    redirect_to master_path
    else
    flash[:danger] = '他の所持スキルと紐づいているため削除できません。'
    redirect_to edit_skill_path
  end
end
  
  
  def search 
  @name = params[:search]
  @results = Skill.where('name LIKE ?', "%#{params[:search]}%")
  @categories = Category.order(created_at: :desc)
  @skills = Skill.order(created_at: :desc)
  end
  
  private

  def skill_params
    params.require(:skill).permit(:name, :category_id, :user_id)
  end
  
  def edit_params
    params.require(:skill).permit(:name, :category_id,:user_id,:display)
end
end

app/views/skills/edit.html.erb
<%= form_for(@skill) do |f| %>

          <div class="form-group">
            <%= f.label :name, 'スキル名' %>
            <%= f.text_field :name, class: 'form-control' %>
          </div>



          <div class="form-group">
            <%= f.label :category_id, 'カテゴリー' %>
            <br>
            <%= f.collection_select :category_id, Category.all, :id, :name, {}, {class: 'form-control'} %>
          </div>
          
          <div class="form-group">
            <%= f.label :user_id, '投稿者' %>
            <br>
            <%= f.collection_select :user_id, User.all, :id, :name, {}, {class: 'form-control'} %>
          </div>

          
          
          <div class="form-group">
            <%= f.label :display, '表示順' %>
            <%= f.text_field :display, class: 'form-control' %>
          </div>
          
          <div class="text-right">
            <%= f.submit '登録する', class: 'btn btn-primary' %>
          </div>
<% end %>

<%= link_to "削除", @skill, method: :delete, data: { confirm: "You sure?" }, class: 'btn btn-danger' %>
<%= link_to '戻る',master_path, class:"btn btn-default" %>

app/views/skills/index.html.erb
<% if current_user.id == 2 %>
<%= link_to 'マスターメニュー',master_path, class:"btn btn-default" %>
<% end %>
<h1 class="text-center">スキル検索</h1>

<br>
  <%= form_tag(search_path, method: :get) do %>
  <div class="form-inline col-xs-offset-5">
    <%= text_field_tag :search,'',class:'form-control',placeholder:'スキル名' %>
    <%= submit_tag '検索',class: 'btn btn-primary' %>

  </div>
  <% end %>

<br><br>




<% if @categories.any? %>
<% @categories.each do |category| %>
<div class="panel-group col-xs-offset-2 col-xs-8">
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapse<%= category.id %>">▼<%= category.name %></a>
      </h4>
    </div>

    <div id="collapse<%= category.id %>" class="panel-collapse collapse in">
      <ul class="list-group">
        <% category.skills.each do |skill| %>
        <li class="list-group-item">
          <table class="table-origin">
            <tbody>
              <tr>
                <td class="col-xs-8 font-origin"><%= link_to skill.name, skill_path(skill.id) %></td>
                
                <th class="col-xs-1 table-bordered text-center">☆<br><%= skill.haveskills.where(assessment:1).count %></th>
                <th class="col-xs-1 table-bordered text-center">◯<br><%= skill.haveskills.where(assessment:2).count %></th>
                <th class="col-xs-1 table-bordered text-center">△<br><%= skill.haveskills.where(assessment:3).count %></th>
                <th class="col-xs-1 table-bordered text-center">×<br><%= skill.haveskills.where(assessment:4).count %></th>
              </tr>
              
            </tbody>
          </table>
        </li>
        <% end %>
      </ul>
      </div>

    
  </div>
</div>
<% end %>
<% end %>

app/views/skills/new.html.erb
<div class="row">
  <div class="col-xs-offset-3 col-xs-6">
    <div class="panel panel-primary">
      
        <div class="panel-heading">新規スキル追加</div>
        <div class="panel-body">
          <p class="">・ここで登録したスキルは全社員の未登録スキルに追加されます。</p>
          <p class="">・ふさわしいカテゴリがない場合は、「その他」カテゴリで追加してください。</p>
          <br>
        <%= form_for(@skill) do |f| %>
        <div class="form-group col-xs-offset-1 col-xs-10">
          <%= f.label :category_id, 'カテゴリ',class:'col-xs-12' %><br>
          <%= f.collection_select :category_id, Category.order(display: :asc), :id, :name, {}, {class: 'form-control'} %>
        </div>
          <div class="form-group col-xs-offset-1 col-xs-10">
          <%= f.label :name, 'スキル名',class:'col-xs-12' %>
          <%= f.text_field :name, class: 'form-control' %>
        </div>
        
        <%= hidden_field_tag :user_id, current_user.id %>
        
        <div class="text-right col-xs-offset-1 col-xs-10">
            <%= f.submit '登録する', class: 'btn btn-primary' %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/skills/search.html.erb
<h1 class="text-center">スキル検索</h1>

<br>
  <%= form_tag(search_path, method: :get) do %>
  <div class="form-inline col-xs-offset-5">
    <%= text_field_tag :search,'',class:'form-control',value: @name %>
    <%= submit_tag '検索',class: 'btn btn-primary' %>

  </div>
  <% end %>

<br><br>



<% if @results.any? %>


<% @categories.each do |category| %>

<% if @results.where(category_id: category.id).count != 0 %>



<div class="panel-group col-xs-offset-2 col-xs-8">
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapse<%= category.id %>">▼<%= category.name %></a>
      </h4>
    </div>

    <div id="collapse<%= category.id %>" class="panel-collapse collapse in">
      <ul class="list-group">
        <% @results.each do |skill| %>
        <% if skill.category_id == category.id %>
        <li class="list-group-item">
          <table class="table-origin">
            <tbody>
              <tr>
                <td class="col-xs-8 font-origin"><%= link_to skill.name, skill_path(skill.id) %></td>
                <th class="col-xs-1 table-bordered text-center">☆<br><%= skill.haveskills.where(assessment:1).count %></th>
                <th class="col-xs-1 table-bordered text-center">◯<br><%= skill.haveskills.where(assessment:2).count %></th>
                <th class="col-xs-1 table-bordered text-center">△<br><%= skill.haveskills.where(assessment:3).count %></th>
                <th class="col-xs-1 table-bordered text-center">×<br><%= skill.haveskills.where(assessment:4).count %></th>
              </tr>
            </tbody>
          </table>
        </li>
        <% end %>
        <% end %>
      </ul>
      </div>

    
  </div>
</div>




<% end %>
<% end %>


<% else %>
<p class="text-center">該当するスキルはありません</p>
<% end %>

app/views/skills/show.html.erb
<div class="panel-group col-xs-offset-2 col-xs-8">
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h4 class="panel-title text-center">
      <%= @skill.name %>
      </h4>
    </div>
    <div class="panel-body">

     

<h1 class="text-center col-xs-12">☆：<%= @skill.haveskills.where(assessment:1).count %>人</h1>

       <div class="col-xs-offset-1 col-xs-10">
         
        <table class="table table-bordered col-xs-10 text-center">
            <tbody>
              <% @skill.haveskills.where(assessment:1).joins(user: :department).order("departments.display").each do |have| %>
              <tr>
                <td class="col-xs-4">
                <%= have.user.department.name %>
                </td>
                <td class="col-xs-3">
                <%= link_to have.user.name, user_path(have.user_id) %>
                </td>
                
              </tr>
              <% end %>
            </tbody>
          </table>
         

          </div>
           <div class="col-xs-12"><p class="box">　</p></div>
          
          <h2 class="text-center col-xs-12">◯：<%= @skill.haveskills.where(assessment:2).count %>人</h2>

        <div class="col-xs-offset-1 col-xs-10">
          
        <table class="table table-bordered col-xs-10 text-center">
            <tbody>
              <% @skill.haveskills.where(assessment:2).joins(user: :department).order("departments.display").each do |have| %>
              <tr>
                
                <td class="col-xs-4">
                <%= have.user.department.name %>
                </td>
                <td class="col-xs-3">
                <%= link_to have.user.name, user_path(have.user_id) %>
                </td>
              </tr>
              <% end %>
            </tbody>
          </table>

        </div>
        <div class="col-xs-12"><p class="box">　</p></div>
        
        <p class="text-center col-xs-12">△：<%= @skill.haveskills.where(assessment:3).count %>人</p>
          
        <p class="text-center col-xs-12">×：<%= @skill.haveskills.where(assessment:4).count %>人<br><br><br><br></p>
        
 
        <p class = "text-center col-xs-12">※　△と×のユーザは表示されません</p>
        </div>
        <div class="panel-footer text-right">
          
          カテゴリ：<%= @skill.category.name %><br>
          作成者：<%= @skill.user.name %>
        </div>

</div>
</div>